export const ChapterData = [
    {
        chapter: 'Chapter 1',
        title: 'The Beginning',
        content: "Hi! I\'m Eggzuki! Your Egg friend warrior who got separated with my master. What happened? Oh now you\'re asking.\nSo here is my story...\n\nOn the vast land of metaverse, my master and I were travelling across borders. Exploring different things and oblivious places. We were crossing the desert. It was scorching hot and we are still too far to the next city. A silhouette of a man appeared not too far from us. The man approached us in incredible speed. I saw him smiling! Was that a smirk? Oh shoot! We are not in great shape to defend ourselves. We are drained. I looked into my master's face and realized, he is smiling too! Is he okay? The man approaching us suddenly stopped and he said \"Yo!\". A greeting from unknown man. He was a tailed-human with scales. My master knew him!\n\nWe were invited in the man's guild. We went inside their tavern and the members warmly welcomed us. They are just a small guild. But their reputation is undeniable. We got invited in their guild and we didn't hesitate to accept the offer.\n\nDuring our stint, we learned many things. There are friendly guild wars happening and we tried joining in. The first match is a toss coin. You should be good at predicting if the coin will face up or down. Do you predict future? Well, you can adjust the leverage if you are brave enough.\n\nThe next one is battle of cute monsters. Trainers are upgrading their teams in order for them to reach the top. Top trainers were rewarded generously. We tried to train ours. But there are better trainers against us. But at least, we enjoyed!\n\nNot too far away, a race of robotic horses is being conducted. Master and I went to see the tournament and we were in awe watching horses from different leagues sprint in a lightning speed. Suddenly, two massive explosions rocked the arena. One could hear nothing but the screams of terrified people. Others gone mad. Many men had been killed. And others are wounded. With this fortuitous event, it caused fear, uncertainty, and doubt to people.\n\nChaos dominated the once lively and amusing stadium. Fire and smoke everywhere. My master tried to help others to get back on their feet. Until I noticed that master is now nowhere to be found. I tried searching everywhere. But because of the smoke, I can't see any. I've waited until the arena is cleared but there are no signs of him. He was wearing straw-made clothes. He belongs to the Garden. I need to find him immediately. Where is he?\n\nTo be continued...",
    },
    {
        chapter: 'Chapter 2',
        title: 'The Second',
        content: "To be continued...",
    },
]